main:
	clang++ *.cpp ../glad/src/glad.c -o main -I ../glad/include -lSDL3 -lSDL3_image -lSDL3_ttf -w

linuxbrew:
	clang++ *.cpp ../glad/src/glad.c -o main -I /home/linuxbrew/.linuxbrew/include -I ../glad/include -L /home/linuxbrew/.linuxbrew/lib -lSDL3 -lSDL3_image -lSDL3_ttf -w

dummy: