window:
	clang++ *.cpp ../glad/src/glad.c -o main -I ../glad/include -lSDL3 -lSDL3_image -lSDL3_ttf -w

linuxbrew:
	clang++ *.cpp ../glad/src/glad.c -o main -I /home/linuxbrew/.linuxbrew/Cellar/sdl2/*/include -I /home/linuxbrew/.linuxbrew/include -I ../glad/include -L /home/linuxbrew/.linuxbrew/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lglfw -w

dummy:
